- name: install keepalived on lb nodes
  package: name={{item}}
  with_items:
   - keepalived

- name: create keepalived.conf
  template: src=../templates/keepalived.conf dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: restart keepalived
  service: 
    name: keepalived 
    state: restarted 
    enabled: yes
