---
- hosts:                lb
  become:               true
  gather_facts:         false
  serial:               1

  tasks:

    - name: open port 80
      firewalld:
        port: 80/tcp
        permanent: true
        immediate: yes
        state: enabled

    - name: open port 443
      firewalld:
        port: 443/tcp
        permanent: true
        immediate: yes
        state: enabled
    
    - name: open port 2379
      firewalld:
        port: 2379/tcp
        permanent: true
        immediate: yes
        state: enabled

    - name: restart firewalld
      service: 
        name: firewalld
        state: restarted

    - name: update haproxy config on lb
      template:
        src: templates/haproxy.cfg
        dest: haproxy.cfg
      when: routervialb is defined and routervialb == true
      delegate_to: localhost

    - name: copy haproxy cfg to lb
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
