---

- hosts: localhost
  gather_facts: false

  tasks:


  - name: copy kubeconfig
    fetch: 
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes      
    delegate_to: "{{groups['masters'] | first}}"

  - name: label new nodes with project label
    shell: oc --config=../kubeconfig label node {{item}} project={{projectName}}
    with_items:
      - "{{groups['new_nodes']}}"

  - name: update remote inventory ini file | clone repo
    shell: 'GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone {{gitlabUrl}}/{{repoName}}.git'

  - name: update remote inventory ini file | change new_nodes to nodes
    lineinfile:
      path: "{{repoName}}/inventories/{{dynamicinvfile}}"
      regexp: '^new_nodes'
      line: nodes

  - name: update remote inventory ini file | commit and push to repo
    shell:  'cd {{repoName}} && git add . && git commit . "." && GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push origin master'
