---

- hosts: localhost
  gather_facts: false
  become: true

  tasks:


  - name: copy kubeconfig
    fetch: 
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes      
    delegate_to: "{{groups['masters'] | first}}"

  - name: label new nodes with project label
    shell: oc --config=../kubeconfig label node {{item}} project={{projectName}}
    with_items:
      - "{{groups['new_nodes']}}"
    ignore_errors: yes

  - name: prepare repo clone dir
    file:
      path: clonedrepo/
      state: directory

  - name: update remote inventory ini file | clone repo
    git: 
      repo: '{{gitlabUrl}}/{{repoName}}.git'
      dest: clonedrepo/
      clone: yes
      update: yes
      force: yes

  - name: update remote inventory ini file | change new_nodes to nodes
    lineinfile:
      path: "clonedrepo/inventories/{{dynamicinvfile}}"
      regexp: '^new_nodes'
      line: nodes

  - name: update remote inventory ini file | commit and push to repo
    shell:  'cd clonedrepo/ && git add . && git commit . "." && git push origin master'
